### PR TITLE
AITOOL-2421: review vulnerabilities in web fcm demo repo

### PR DESCRIPTION
**Pull request by pegondo**
# [AITOOL-2421](https://lampkicking.atlassian.net/browse/AITOOL-2421)

## What?
Updated project dependencies to remove some of the vulnerabilities of the repository.

As `webpack-cli` and `webpack-dev-server`'s versions were upgraded to a new mayor, some code changes were also made.

**NOTE**: Not all the vulnerabilities were removed, as some of them required webpack dependencies to be updating, including breaking changes which would imply changes on the code.

`npm audit` output:

```
# npm audit report

ansi-regex  >2.1.1 <5.0.1
Severity: moderate
 Inefficient Regular Expression Complexity in chalk/ansi-regex - https://github.com/advisories/GHSA-93q8-gq69-wqmw
fix available via `npm audit fix`
node_modules/@parcel/logger/node_modules/ansi-regex
node_modules/ansi-regex
node_modules/ora/node_modules/ansi-regex
  strip-ansi  4.0.0 - 5.2.0
  Depends on vulnerable versions of ansi-regex
  node_modules/@parcel/logger/node_modules/strip-ansi
  node_modules/ora/node_modules/strip-ansi
    @parcel/logger  <=1.11.1
    Depends on vulnerable versions of strip-ansi
    node_modules/@parcel/logger
      parcel-bundler  *
      Depends on vulnerable versions of @parcel/logger
      Depends on vulnerable versions of css-modules-loader-core
      Depends on vulnerable versions of fast-glob
      Depends on vulnerable versions of node-forge
      Depends on vulnerable versions of postcss
      node_modules/parcel-bundler
        @svgr/parcel-plugin-svgr  <=5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        Depends on vulnerable versions of parcel-bundler
        node_modules/@svgr/parcel-plugin-svgr
    ora  2.0.0 - 4.0.2
    Depends on vulnerable versions of strip-ansi
    node_modules/ora

glob-parent  <5.1.2
Severity: high
Regular expression denial of service - https://github.com/advisories/GHSA-ww39-953v-wcq6
fix available via `npm audit fix`
node_modules/chokidar/node_modules/glob-parent
node_modules/parcel-bundler/node_modules/glob-parent
  chokidar  1.0.0-rc1 - 2.1.8
  Depends on vulnerable versions of glob-parent
  node_modules/chokidar
    @parcel/watcher  <=1.12.1
    Depends on vulnerable versions of chokidar
    node_modules/@parcel/watcher
  fast-glob  <=2.2.7
  Depends on vulnerable versions of glob-parent
  node_modules/parcel-bundler/node_modules/fast-glob
    parcel-bundler  *
    Depends on vulnerable versions of @parcel/logger
    Depends on vulnerable versions of css-modules-loader-core
    Depends on vulnerable versions of fast-glob
    Depends on vulnerable versions of node-forge
    Depends on vulnerable versions of postcss
    node_modules/parcel-bundler
      @svgr/parcel-plugin-svgr  <=5.5.0
      Depends on vulnerable versions of @svgr/plugin-svgo
      Depends on vulnerable versions of parcel-bundler
      node_modules/@svgr/parcel-plugin-svgr

node-fetch  <=2.6.6
Severity: high
The `size` option isn't honored after following a redirect in node-fetch - https://github.com/advisories/GHSA-w7rc-rwvf-8q5r
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
No fix available
node_modules/node-fetch
  @tensorflow/tfjs-core  1.1.0 - 2.4.0
  Depends on vulnerable versions of node-fetch
  node_modules/@tensorflow/tfjs-core
    face-api.js  >=0.20.1
    Depends on vulnerable versions of @tensorflow/tfjs-core
    node_modules/face-api.js
      @getyoti/react-face-capture  *
      Depends on vulnerable versions of face-api.js
      node_modules/@getyoti/react-face-capture

node-forge  <1.0.0
Severity: moderate
Open Redirect in node-forge - https://github.com/advisories/GHSA-8fr3-hfg3-gpgp
No fix available
node_modules/node-forge
  parcel-bundler  *
  Depends on vulnerable versions of @parcel/logger
  Depends on vulnerable versions of css-modules-loader-core
  Depends on vulnerable versions of fast-glob
  Depends on vulnerable versions of node-forge
  Depends on vulnerable versions of postcss
  node_modules/parcel-bundler
    @svgr/parcel-plugin-svgr  <=5.5.0
    Depends on vulnerable versions of @svgr/plugin-svgo
    Depends on vulnerable versions of parcel-bundler
    node_modules/@svgr/parcel-plugin-svgr
  yoti  *
  Depends on vulnerable versions of node-forge
  node_modules/yoti

nth-check  <2.0.1
Severity: moderate
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix --force`
Will install react-scripts@3.0.1, which is a breaking change
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/svgo/node_modules/css-select
    svgo  1.0.0 - 1.3.2
    Depends on vulnerable versions of css-select
    node_modules/svgo
      @svgr/plugin-svgo  <=5.5.0
      Depends on vulnerable versions of svgo
      node_modules/@svgr/plugin-svgo
        @svgr/parcel-plugin-svgr  <=5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        Depends on vulnerable versions of parcel-bundler
        node_modules/@svgr/parcel-plugin-svgr
        @svgr/webpack  4.0.0 - 5.5.0
        Depends on vulnerable versions of @svgr/plugin-svgo
        node_modules/@svgr/webpack
          react-scripts  >=2.1.4
          Depends on vulnerable versions of @svgr/webpack
          Depends on vulnerable versions of resolve-url-loader
          node_modules/react-scripts
      htmlnano  >=0.1.1
      Depends on vulnerable versions of cssnano
      Depends on vulnerable versions of purgecss
      Depends on vulnerable versions of svgo
      Depends on vulnerable versions of uncss
      node_modules/htmlnano
      postcss-svgo  <=5.0.0-rc.2
      Depends on vulnerable versions of postcss
      Depends on vulnerable versions of svgo
      node_modules/postcss-svgo

postcss  <=8.2.12
Severity: moderate
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-hwj9-h5mp-3pm3
Regular Expression Denial of Service in postcss - https://github.com/advisories/GHSA-566m-qj78-rww5
fix available via `npm audit fix --force`
Will install react-scripts@3.0.1, which is a breaking change
node_modules/css-modules-loader-core/node_modules/postcss
node_modules/postcss
node_modules/postcss-modules-extract-imports/node_modules/postcss
node_modules/postcss-modules-local-by-default/node_modules/postcss
node_modules/postcss-modules-scope/node_modules/postcss
node_modules/postcss-modules-values/node_modules/postcss
node_modules/purgecss/node_modules/postcss
  css-declaration-sorter  <=5.1.2
  Depends on vulnerable versions of postcss
  node_modules/css-declaration-sorter
  css-modules-loader-core  *
  Depends on vulnerable versions of postcss
  Depends on vulnerable versions of postcss-modules-values
  node_modules/css-modules-loader-core
    parcel-bundler  *
    Depends on vulnerable versions of @parcel/logger
    Depends on vulnerable versions of css-modules-loader-core
    Depends on vulnerable versions of fast-glob
    Depends on vulnerable versions of node-forge
    Depends on vulnerable versions of postcss
    node_modules/parcel-bundler
      @svgr/parcel-plugin-svgr  <=5.5.0
      Depends on vulnerable versions of @svgr/plugin-svgo
      Depends on vulnerable versions of parcel-bundler
      node_modules/@svgr/parcel-plugin-svgr
  cssnano  <=4.1.11
  Depends on vulnerable versions of cssnano-preset-default
  Depends on vulnerable versions of postcss
  node_modules/cssnano
    htmlnano  >=0.1.1
    Depends on vulnerable versions of cssnano
    Depends on vulnerable versions of purgecss
    Depends on vulnerable versions of svgo
    Depends on vulnerable versions of uncss
    node_modules/htmlnano
  cssnano-preset-default  <=4.0.8
  Depends on vulnerable versions of postcss
  node_modules/cssnano-preset-default
  cssnano-util-raw-cache  *
  Depends on vulnerable versions of postcss
  node_modules/cssnano-util-raw-cache
  postcss-calc  4.1.0 - 7.0.5
  Depends on vulnerable versions of postcss
  node_modules/postcss-calc
  postcss-colormin  <=4.0.3
  Depends on vulnerable versions of postcss
  node_modules/postcss-colormin
  postcss-convert-values  <=4.0.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-convert-values
  postcss-discard-comments  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-discard-comments
  postcss-discard-duplicates  1.1.0 - 4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-discard-duplicates
  postcss-discard-empty  1.1.0 - 4.0.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-discard-empty
  postcss-discard-overridden  <=4.0.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-discard-overridden
  postcss-merge-longhand  <=4.0.11
  Depends on vulnerable versions of postcss
  Depends on vulnerable versions of stylehacks
  node_modules/postcss-merge-longhand
  postcss-merge-rules  <=4.0.3
  Depends on vulnerable versions of postcss
  node_modules/postcss-merge-rules
  postcss-minify-font-values  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-minify-font-values
  postcss-minify-gradients  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-minify-gradients
  postcss-minify-params  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-minify-params
  postcss-minify-selectors  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-minify-selectors
  postcss-modules-extract-imports  <=2.0.0
  Depends on vulnerable versions of postcss
  node_modules/postcss-modules-extract-imports
  postcss-modules-local-by-default  <=3.0.3
  Depends on vulnerable versions of postcss
  node_modules/postcss-modules-local-by-default
  postcss-modules-scope  <=2.2.0
  Depends on vulnerable versions of postcss
  node_modules/postcss-modules-scope
  postcss-modules-values  <=3.0.0
  Depends on vulnerable versions of postcss
  node_modules/postcss-modules-values
  postcss-normalize-charset  <=4.0.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-charset
  postcss-normalize-display-values  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-display-values
  postcss-normalize-positions  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-positions
  postcss-normalize-repeat-style  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-repeat-style
  postcss-normalize-string  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-string
  postcss-normalize-timing-functions  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-timing-functions
  postcss-normalize-unicode  <=4.0.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-unicode
  postcss-normalize-url  1.1.0 - 4.0.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-url
  postcss-normalize-whitespace  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-normalize-whitespace
  postcss-ordered-values  <=4.1.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-ordered-values
  postcss-reduce-initial  <=4.0.3
  Depends on vulnerable versions of postcss
  node_modules/postcss-reduce-initial
  postcss-reduce-transforms  <=4.0.2
  Depends on vulnerable versions of postcss
  node_modules/postcss-reduce-transforms
  postcss-svgo  <=5.0.0-rc.2
  Depends on vulnerable versions of postcss
  Depends on vulnerable versions of svgo
  node_modules/postcss-svgo
  postcss-unique-selectors  <=4.0.1
  Depends on vulnerable versions of postcss
  node_modules/postcss-unique-selectors
  purgecss  <=3.0.0
  Depends on vulnerable versions of postcss
  node_modules/purgecss
  resolve-url-loader  0.0.1-experiment-postcss || 3.0.0-alpha.1 - 4.0.0
  Depends on vulnerable versions of postcss
  node_modules/resolve-url-loader
    react-scripts  >=2.1.4
    Depends on vulnerable versions of @svgr/webpack
    Depends on vulnerable versions of resolve-url-loader
    node_modules/react-scripts
  stylehacks  <=4.0.3
  Depends on vulnerable versions of postcss
  node_modules/stylehacks
  uncss  >=0.14.0
  Depends on vulnerable versions of postcss
  node_modules/uncss

64 vulnerabilities (55 moderate, 9 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.
```

After all the changes, it passed from being **125 vulnerabilities (104 moderate, 19 high, 2 critical)** to **64 vulnerabilities (55 moderate, 9 high)**, all of them caused because of the `react`, `react-dom` and `face-capture-module` dependencies of the project.

Why?
Because GitHub reported vulnerabilities on the repository.

### CODE REVIEW

**Review by pegondo — COMMENTED** [review]
Do you think I should update `webpack` dependencies to solve all the vulnerabilities on this PR? Keep in mind that this will imply webpack code changes.

**Review by bernar95 — APPROVED** [review]

**Comment by tonygcs** [comment]
> Do you think I should update `webpack` dependencies to solve all the vulnerabilities on this PR? Keep in mind that this will imply webpack code changes.

For me it's fine if you change the code to remove all the vulnerabilities.

**Comment by MiguelJS** [comment]
> > Do you think I should update `webpack` dependencies to solve all the vulnerabilities on this PR? Keep in mind that this will imply webpack code changes.
> 
> For me it's fine if you change the code to remove all the vulnerabilities.

Agree, the goal of the ticket is to solve all the vulnerabilities

**Comment by pegondo** [comment]
> > > Do you think I should update `webpack` dependencies to solve all the vulnerabilities on this PR? Keep in mind that this will imply webpack code changes.
> > 
> > 
> > For me it's fine if you change the code to remove all the vulnerabilities.
> 
> Agree, the goal of the ticket is to solve all the vulnerabilities

Sounds good to me. I will convert this PR into a draft, work on this changes and convert it back to a PR when they are done.

**Comment by tonygcs** [comment]
I guess we will fix the vulnerabilities for the face capture module but what are we going to do with the others that this PR didn't resolve?

**Comment by pegondo** [comment]
> @pegondo I guess we will fix the vulnerabilities for the face capture module but what are we going to do with the others that this PR didn't resolve?

They are there because the latest versions of the current dependencies also have them. Can you think of any solution.

**Comment by tonygcs** [comment]
> They are there because the latest versions of the current dependencies also have them. Can you think of any solution.

Maybe we can user other packages but for a small demo about how to use the FCM I guess it's fine as it is right now.

**Review by tonygcs — APPROVED** [review]

**Review by MiguelJS — APPROVED** [review]

**Review by DionisioRD — APPROVED** [review]

**Review by MatteoWebDeveloper — APPROVED** [review]

**Pull request merged**
